# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eservices.proto\x12\x0eusermanagement\"/\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"7\n\x11\x43reateUserRequest\x12\"\n\x04user\x18\x01 \x01(\x0b\x32\x14.usermanagement.User\"\x1c\n\x0eGetUserRequest\x12\n\n\x02id\x18\x01 \x01(\t\"7\n\x11UpdateUserRequest\x12\"\n\x04user\x18\x01 \x01(\x0b\x32\x14.usermanagement.User\"\x1f\n\x11\x44\x65leteUserRequest\x12\n\n\x02id\x18\x01 \x01(\t\"C\n\x0cUserResponse\x12\"\n\x04user\x18\x01 \x01(\x0b\x32\x14.usermanagement.User\x12\x0f\n\x07message\x18\x02 \x01(\t\"+\n\x12ImportUsersRequest\x12\x15\n\rcsv_file_path\x18\x01 \x01(\t\">\n\x13ImportUsersResponse\x12\x16\n\x0eimported_count\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t2\xa8\x03\n\x0eUserManagement\x12O\n\nCreateUser\x12!.usermanagement.CreateUserRequest\x1a\x1c.usermanagement.UserResponse\"\x00\x12I\n\x07GetUser\x12\x1e.usermanagement.GetUserRequest\x1a\x1c.usermanagement.UserResponse\"\x00\x12O\n\nUpdateUser\x12!.usermanagement.UpdateUserRequest\x1a\x1c.usermanagement.UserResponse\"\x00\x12O\n\nDeleteUser\x12!.usermanagement.DeleteUserRequest\x1a\x1c.usermanagement.UserResponse\"\x00\x12X\n\x0bImportUsers\x12\".usermanagement.ImportUsersRequest\x1a#.usermanagement.ImportUsersResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'services_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USER']._serialized_start=34
  _globals['_USER']._serialized_end=81
  _globals['_CREATEUSERREQUEST']._serialized_start=83
  _globals['_CREATEUSERREQUEST']._serialized_end=138
  _globals['_GETUSERREQUEST']._serialized_start=140
  _globals['_GETUSERREQUEST']._serialized_end=168
  _globals['_UPDATEUSERREQUEST']._serialized_start=170
  _globals['_UPDATEUSERREQUEST']._serialized_end=225
  _globals['_DELETEUSERREQUEST']._serialized_start=227
  _globals['_DELETEUSERREQUEST']._serialized_end=258
  _globals['_USERRESPONSE']._serialized_start=260
  _globals['_USERRESPONSE']._serialized_end=327
  _globals['_IMPORTUSERSREQUEST']._serialized_start=329
  _globals['_IMPORTUSERSREQUEST']._serialized_end=372
  _globals['_IMPORTUSERSRESPONSE']._serialized_start=374
  _globals['_IMPORTUSERSRESPONSE']._serialized_end=436
  _globals['_USERMANAGEMENT']._serialized_start=439
  _globals['_USERMANAGEMENT']._serialized_end=863
# @@protoc_insertion_point(module_scope)
