# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import services_pb2 as services__pb2


class UserManagementStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateUser = channel.unary_unary(
                '/usermanagement.UserManagement/CreateUser',
                request_serializer=services__pb2.CreateUserRequest.SerializeToString,
                response_deserializer=services__pb2.UserResponse.FromString,
                )
        self.GetUser = channel.unary_unary(
                '/usermanagement.UserManagement/GetUser',
                request_serializer=services__pb2.GetUserRequest.SerializeToString,
                response_deserializer=services__pb2.UserResponse.FromString,
                )
        self.UpdateUser = channel.unary_unary(
                '/usermanagement.UserManagement/UpdateUser',
                request_serializer=services__pb2.UpdateUserRequest.SerializeToString,
                response_deserializer=services__pb2.UserResponse.FromString,
                )
        self.DeleteUser = channel.unary_unary(
                '/usermanagement.UserManagement/DeleteUser',
                request_serializer=services__pb2.DeleteUserRequest.SerializeToString,
                response_deserializer=services__pb2.UserResponse.FromString,
                )
        self.ImportUsers = channel.unary_unary(
                '/usermanagement.UserManagement/ImportUsers',
                request_serializer=services__pb2.ImportUsersRequest.SerializeToString,
                response_deserializer=services__pb2.ImportUsersResponse.FromString,
                )


class UserManagementServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ImportUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserManagementServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUser,
                    request_deserializer=services__pb2.CreateUserRequest.FromString,
                    response_serializer=services__pb2.UserResponse.SerializeToString,
            ),
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=services__pb2.GetUserRequest.FromString,
                    response_serializer=services__pb2.UserResponse.SerializeToString,
            ),
            'UpdateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUser,
                    request_deserializer=services__pb2.UpdateUserRequest.FromString,
                    response_serializer=services__pb2.UserResponse.SerializeToString,
            ),
            'DeleteUser': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUser,
                    request_deserializer=services__pb2.DeleteUserRequest.FromString,
                    response_serializer=services__pb2.UserResponse.SerializeToString,
            ),
            'ImportUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.ImportUsers,
                    request_deserializer=services__pb2.ImportUsersRequest.FromString,
                    response_serializer=services__pb2.ImportUsersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'usermanagement.UserManagement', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UserManagement(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/usermanagement.UserManagement/CreateUser',
            services__pb2.CreateUserRequest.SerializeToString,
            services__pb2.UserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/usermanagement.UserManagement/GetUser',
            services__pb2.GetUserRequest.SerializeToString,
            services__pb2.UserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/usermanagement.UserManagement/UpdateUser',
            services__pb2.UpdateUserRequest.SerializeToString,
            services__pb2.UserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/usermanagement.UserManagement/DeleteUser',
            services__pb2.DeleteUserRequest.SerializeToString,
            services__pb2.UserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ImportUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/usermanagement.UserManagement/ImportUsers',
            services__pb2.ImportUsersRequest.SerializeToString,
            services__pb2.ImportUsersResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
